import json
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).parent.resolve()
CONFIG_DIR = SCRIPT_DIR / "config"

ares_config_template = """\
#_______________________________________________________________________________
#    ######   ####     ##             #####   #####     ##    #    #    ##
#    #       #        #  #            #    #  #    #   #  #   ##  ##   #  #
#    #####    ####   ######           #    #  #####   ######  # ## #  ######
#    #            #  #    #           #    #  #    #  #    #  #    #  #    #
#____######__#####___#____#___________#####___#____#__#____#__#____#__#____#____
#===============================================================================
#            ESA Debris Risk Assessment and Mitigation Analysis Tool
#                       Assessment of Risk Events Statistics
#-------------------------------------------------------------------------------
#                                 DRAMA  - ARES
#-------------------------------------------------------------------------------
# 'ares.cfg' specifies the configuration settings for the ARES application
# within the DRAMA2 tool. This file must be stored in the same directory
# than the ARES executable file. It contains file paths
# relative to this location.
#---------------------------------------------------------------------------
# No.      File number (Do not edit!)
# Name:    Filename
#             Filenames must span from column 12 to 21
#             *name* files are generated by the tool,
#                    Do not change these names!
# Path:    Path relative to the location of this file
#             It must start in column 25, must be between quoutes (')
#             and should not be longer than 20 characters
#             A trailing slash must be provided at the end
# Comment: Description of file
#-------------------------------------------------------------------------------
#No        Filename     Path         Comment
#-------------------------------------------------------------------------------
#
 1         ares.cfg     ''             THIS FILE; MUST BE IN PATH OF 'ares.exe'
 2         ares.err     ''             'error messages'
 3         ares.inp     'input/'        'Input parameters'
 4                      '{master_data}'  'Path to MASTER data files'
 5                      'input/focus/'  'Path to FOCUS files'
 6         *name*.cp    'output/'       'Annual Collision Probability'
 7         *name*.man   'output/'       'Avoidance Manoeuvres Statistics'
 8         *name*.rr    'output/'       'Risk'
 9         *name*.frr   'output/'       'Fractional Risk'
 10        *name*.far   'output/'       'False Alarm Rate'
 11        *name*.rra   'output/'       'RR vs ACPL'
 12        *name*.dv    'output/'       'Delta-V Requirements'
 13        *name*.pmf   'output/'       'Propellant Mass Fraction'
 14        *name*.gnu   'output/'       'Main gnuplot driver file'
"""

drama_gui_config_template = """\
#ESA Application Settings
#Thu Apr 29 16:27:12 CEST 2021
DRAMA3WorkspaceDirectory={drama3_workspace_directory}
ARESBinary={ares_binary}
"""


def drama_installation_config(version):
    """ Create DRAMA3 installation config file """
    data = {"drama_installation_path": str(CONFIG_DIR)}
    with open(CONFIG_DIR / version / "config.json", "w") as f:
        json.dump(data, f)


def ares_config(master_data_path):
    """ Create ARES config file """
    with open(CONFIG_DIR / "TOOLS" / "ARES" / "ares.cfg", "w") as f:
        f.write(ares_config_template.replace("{master_data}", master_data_path))


def drama_gui_config(config_path, binary_path):
    """ Create DRAMA GUI config file """
    with open(CONFIG_DIR / "drama-gui.cfg", "w") as f:
        f.write(
            drama_gui_config_template.replace(
                "{drama3_workspace_directory}", config_path
            ).replace("{ares_binary}", binary_path)
        )


drama_installation_config(version="3.0.4")
ares_config(master_data_path=f'{SCRIPT_DIR / "config" / "master_data/"}/')
drama_gui_config(str(SCRIPT_DIR / "config" ), f'{SCRIPT_DIR / "config" / "ares_osx"}')

